apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workshop
  template:
    metadata:
      labels:
        app: workshop
    spec:
      containers:
      - name: myapp
        image: workshop/myapp:latest
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http