apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: etcd-deployment
  labels:
    app: workshop
spec:
  replicas: 0
  selector:
    matchLabels:
      app: workshop
  template:
    metadata:
      labels:
        app: workshop
    spec:
      containers:
      - name: etcd
        image: elcolio/etcd:latest
        ports:
        - containerPort: 4001
          protocol: TCP