apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    name: etcd
    app: workshop
spec:
  ports:
  - port: 4001
    name: etcd
    targetPort: 4001
  selector:
    name: etcd
    app: workshop