apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: workshop
spec:
  selector:
    name: web 
  type: NodePort
  ports:
   - port: 31380
     targetPort: 8080
     protocol: TCP